//! Runtime validators for tool arguments.
//!
//! These helpers are called by code generated by `#[cognis::tool]`
//! (in `cognis-macros`) after JSON deserialization succeeds but before the
//! tool body runs. A constraint violation returns
//! [`CognisError::ToolValidationError`] with a field-scoped message — which
//! [`BaseTool::run`] already routes through [`ErrorHandler`], allowing agent
//! authors to surface validator messages back to the LLM for self-correction.
//!
//! # Schema/runtime duality
//!
//! Every validator here has a **matching schema attribute** in
//! `#[derive(JsonSchema)]` (see `cognis_macros::JsonSchema`). The schema
//! attribute emits JSON Schema keywords the LLM can see; the runtime helper
//! enforces the same constraint after deserialization. Keeping them in sync
//! is the feature's main purpose — don't add one without the other.

use crate::error::{CognisError, Result};
