//! Typed streaming of structured list output.
//!
//! [`Client::stream_array`] turns a streamed JSON array into a
//! [`RunnableStream`] of validated `T` values, yielding each element as soon
//! as it closes. [`Client::stream_object_partial_value`] instead streams one
//! object as progressively-filled snapshots. Processing is ordinary
//! `futures::StreamExt` iteration.

use serde::de::DeserializeOwned;

use cognis_core::{
    close_partial_json, CognisError, Message, Result, RunnableStream, StreamingJsonArray,
};
use futures::StreamExt;

use crate::Client;

impl Client {
    /// Stream a JSON array as typed elements, each delivered when it closes.
    ///
    /// Different from [`Client::stream_with_tools`], which yields raw text
    /// chunks: this parses the array incrementally and yields validated `T`
    /// values. A malformed element yields one `Err` item for that element and
    /// the stream continues; a provider error is yielded and ends the stream.
    pub async fn stream_array<T: DeserializeOwned + Send + 'static>(
        &self,
        messages: Vec<Message>,
    ) -> Result<RunnableStream<T>> {
        let chunks = self.stream_with_tools(messages, Vec::new()).await?;
        let mut parser = StreamingJsonArray::new();
        let out = async_stream::stream! {
            let mut chunks = chunks;
            while let Some(item) = chunks.next().await {
                match item {
                    Ok(chunk) => {
                        for raw in parser.push_str(&chunk.content) {
                            yield decode::<T>(&raw);
                        }
                    }
                    Err(e) => {
                        yield Err(e);
                        return;
                    }
                }
            }
            for raw in parser.finish() {
                yield decode::<T>(&raw);
            }
        };
        Ok(RunnableStream::new(out))
    }

    /// Stream a single JSON object as progressively-filled snapshots.
    ///
    /// Different from [`Client::stream_array`], which yields whole elements:
    /// each item is the object parsed so far, with open strings, arrays and
    /// objects closed (see [`close_partial_json`]). Snapshots that parse to the
    /// same value as the previous one are skipped. If the provider stream ends
    /// before the object closes, the last good snapshot is the final item; a
    /// provider error is yielded and ends the stream.
    pub async fn stream_object_partial_value(
        &self,
        messages: Vec<Message>,
    ) -> Result<RunnableStream<serde_json::Value>> {
        let chunks = self.stream_with_tools(messages, Vec::new()).await?;
        let out = async_stream::stream! {
            let mut chunks = chunks;
            let mut buf = String::new();
            let mut last: Option<serde_json::Value> = None;
            while let Some(item) = chunks.next().await {
                match item {
                    Ok(chunk) => {
                        buf.push_str(&chunk.content);
                        let snapshot = close_partial_json(&buf)
                            .and_then(|closed| serde_json::from_str::<serde_json::Value>(&closed).ok());
                        if let Some(v) = snapshot {
                            if last.as_ref() != Some(&v) {
                                last = Some(v.clone());
                                yield Ok(v);
                            }
                        }
                    }
                    Err(e) => {
                        yield Err(e);
                        return;
                    }
                }
            }
        };
        Ok(RunnableStream::new(out))
    }

    /// Stream a single JSON object as typed, progressively-filled `T::Partial`.
    ///
    /// Different from [`Client::stream_object_partial_value`], which yields raw
    /// `Value` snapshots: each snapshot is decoded into the all-`Option`
    /// mirror generated by `#[derive(Partial)]`. Snapshots that do not yet fit
    /// the mirror's shape (e.g. a number still arriving as a string) are
    /// skipped rather than erroring; a provider error is yielded and ends the
    /// stream.
    pub async fn stream_object_partial<T: cognis_core::Partial>(
        &self,
        messages: Vec<Message>,
    ) -> Result<RunnableStream<T::Partial>> {
        let values = self.stream_object_partial_value(messages).await?;
        let out = async_stream::stream! {
            let mut values = values;
            while let Some(item) = values.next().await {
                match item {
                    Ok(v) => {
                        if let Ok(p) = serde_json::from_value::<T::Partial>(v) {
                            yield Ok(p);
                        }
                    }
                    Err(e) => {
                        yield Err(e);
                        return;
                    }
                }
            }
        };
        Ok(RunnableStream::new(out))
    }
}

fn decode<T: DeserializeOwned>(raw: &str) -> Result<T> {
    serde_json::from_str(raw)
        .map_err(|e| CognisError::Serialization(format!("element: {e}: {raw}")))
}

#[cfg(test)]
mod tests {
    use crate::chat::{ChatResponse, HealthStatus, StreamChunk};
    use crate::provider::{LLMProvider, Provider};
    use crate::{ChatOptions, Client, ToolDefinition};
    use async_trait::async_trait;
    use cognis_core::{CognisError, Message, Result, RunnableStream};
    use futures::StreamExt;
    use std::sync::Arc;

    #[derive(cognis_macros::Partial)]
    #[allow(dead_code)]
    struct Report {
        title: String,
        score: u32,
    }

    #[derive(serde::Deserialize, Debug, PartialEq)]
    struct Step {
        id: u32,
    }

    /// Streams the scripted text pieces as delta chunks; optionally ends in an error.
    struct ArrProvider {
        pieces: Vec<&'static str>,
        fail_after: bool,
    }

    impl ArrProvider {
        fn new(pieces: &[&'static str]) -> Self {
            Self {
                pieces: pieces.to_vec(),
                fail_after: false,
            }
        }
    }

    #[async_trait]
    impl LLMProvider for ArrProvider {
        fn name(&self) -> &str {
            "arr"
        }
        fn provider_type(&self) -> Provider {
            Provider::Ollama
        }
        async fn chat_completion(&self, _m: Vec<Message>, _o: ChatOptions) -> Result<ChatResponse> {
            unreachable!()
        }
        async fn chat_completion_stream(
            &self,
            _m: Vec<Message>,
            _o: ChatOptions,
        ) -> Result<RunnableStream<StreamChunk>> {
            unreachable!()
        }
        async fn chat_completion_stream_with_tools(
            &self,
            _m: Vec<Message>,
            _t: Vec<ToolDefinition>,
            _o: ChatOptions,
        ) -> Result<RunnableStream<StreamChunk>> {
            let mut chunks: Vec<Result<StreamChunk>> = self
                .pieces
                .iter()
                .map(|s| {
                    Ok(StreamChunk {
                        content: (*s).into(),
                        is_delta: true,
                        is_done: false,
                        finish_reason: None,
                        usage: None,
                        tool_calls_delta: vec![],
                    })
                })
                .collect();
            if self.fail_after {
                chunks.push(Err(CognisError::Internal("boom".into())));
            }
            Ok(RunnableStream::new(futures::stream::iter(chunks)))
        }
        async fn health_check(&self) -> Result<HealthStatus> {
            Ok(HealthStatus::Healthy { latency_ms: 0 })
        }
    }

    fn client(p: ArrProvider) -> Client {
        Client::new(Arc::new(p))
    }

    #[tokio::test]
    async fn stream_array_yields_typed_elements() {
        let c = client(ArrProvider::new(&["[{\"id\":1},", "{\"id\":2}]"]));
        let mut s = c
            .stream_array::<Step>(vec![Message::human("plan")])
            .await
            .unwrap();
        let a = s.next().await.unwrap().unwrap();
        let b = s.next().await.unwrap().unwrap();
        assert_eq!(a, Step { id: 1 });
        assert_eq!(b, Step { id: 2 });
        assert!(s.next().await.is_none());
    }

    #[tokio::test]
    async fn stream_array_reassembles_element_split_across_chunks() {
        let c = client(ArrProvider::new(&["[{\"i", "d\":", "7}", ",{\"id\":8}]"]));
        let got: Vec<Step> = c
            .stream_array::<Step>(vec![Message::human("plan")])
            .await
            .unwrap()
            .map(|r| r.unwrap())
            .collect()
            .await;
        assert_eq!(got, vec![Step { id: 7 }, Step { id: 8 }]);
    }

    #[tokio::test]
    async fn stream_array_yields_err_for_bad_element_and_continues() {
        let c = client(ArrProvider::new(&[
            "[{\"id\":1},{\"id\":\"x\"},{\"id\":3}]",
        ]));
        let got: Vec<Result<Step>> = c
            .stream_array::<Step>(vec![Message::human("plan")])
            .await
            .unwrap()
            .collect()
            .await;
        assert_eq!(got.len(), 3, "got: {got:?}");
        assert_eq!(got[0].as_ref().unwrap(), &Step { id: 1 });
        assert!(
            matches!(got[1], Err(CognisError::Serialization(_))),
            "got: {:?}",
            got[1]
        );
        assert_eq!(got[2].as_ref().unwrap(), &Step { id: 3 });
    }

    #[tokio::test]
    async fn stream_array_yields_nothing_for_empty_array() {
        let c = client(ArrProvider::new(&["[]"]));
        let got: Vec<Result<Step>> = c
            .stream_array::<Step>(vec![Message::human("plan")])
            .await
            .unwrap()
            .collect()
            .await;
        assert!(got.is_empty(), "got: {got:?}");
    }

    #[tokio::test]
    async fn stream_array_propagates_provider_error_and_stops() {
        let mut p = ArrProvider::new(&["[{\"id\":1},"]);
        p.fail_after = true;
        let got: Vec<Result<Step>> = client(p)
            .stream_array::<Step>(vec![Message::human("plan")])
            .await
            .unwrap()
            .collect()
            .await;
        assert_eq!(got.len(), 2, "got: {got:?}");
        assert_eq!(got[0].as_ref().unwrap(), &Step { id: 1 });
        assert!(got[1].is_err());
    }

    #[tokio::test]
    async fn stream_object_partial_value_fills_snapshots_progressively() {
        let c = client(ArrProvider::new(&["{\"a\":1", ",\"b\":2}"]));
        let got: Vec<serde_json::Value> = c
            .stream_object_partial_value(vec![Message::human("obj")])
            .await
            .unwrap()
            .map(|r| r.unwrap())
            .collect()
            .await;
        assert_eq!(
            got,
            vec![
                serde_json::json!({"a": 1}),
                serde_json::json!({"a": 1, "b": 2})
            ],
            "got: {got:?}"
        );
    }

    #[tokio::test]
    async fn stream_object_partial_value_grows_string_value_across_chunks() {
        let c = client(ArrProvider::new(&["{\"msg\":\"he", "llo wor", "ld\"}"]));
        let got: Vec<serde_json::Value> = c
            .stream_object_partial_value(vec![Message::human("obj")])
            .await
            .unwrap()
            .map(|r| r.unwrap())
            .collect()
            .await;
        assert_eq!(
            got,
            vec![
                serde_json::json!({"msg": "he"}),
                serde_json::json!({"msg": "hello wor"}),
                serde_json::json!({"msg": "hello world"}),
            ],
            "got: {got:?}"
        );
    }

    #[tokio::test]
    async fn stream_object_partial_value_skips_duplicate_snapshots() {
        // The second and third chunks add no new parseable content.
        let c = client(ArrProvider::new(&["{\"a\":1", ",", " \"b\":", "2}"]));
        let got: Vec<serde_json::Value> = c
            .stream_object_partial_value(vec![Message::human("obj")])
            .await
            .unwrap()
            .map(|r| r.unwrap())
            .collect()
            .await;
        assert_eq!(
            got,
            vec![
                serde_json::json!({"a": 1}),
                serde_json::json!({"a": 1, "b": 2})
            ],
            "got: {got:?}"
        );
    }

    #[tokio::test]
    async fn stream_object_partial_value_ends_with_last_good_snapshot_when_never_closed() {
        let c = client(ArrProvider::new(&["{\"a\":1,", "\"b\":\"par"]));
        let got: Vec<serde_json::Value> = c
            .stream_object_partial_value(vec![Message::human("obj")])
            .await
            .unwrap()
            .map(|r| r.unwrap())
            .collect()
            .await;
        assert_eq!(
            got.last(),
            Some(&serde_json::json!({"a": 1, "b": "par"})),
            "got: {got:?}"
        );
    }

    #[tokio::test]
    async fn stream_object_partial_value_yields_nothing_without_an_object() {
        let c = client(ArrProvider::new(&["no json ", "here"]));
        let got: Vec<Result<serde_json::Value>> = c
            .stream_object_partial_value(vec![Message::human("obj")])
            .await
            .unwrap()
            .collect()
            .await;
        assert!(got.is_empty(), "got: {got:?}");
    }

    #[tokio::test]
    async fn stream_object_partial_value_propagates_provider_error_and_stops() {
        let mut p = ArrProvider::new(&["{\"a\":1"]);
        p.fail_after = true;
        let got: Vec<Result<serde_json::Value>> = client(p)
            .stream_object_partial_value(vec![Message::human("obj")])
            .await
            .unwrap()
            .collect()
            .await;
        assert_eq!(got.len(), 2, "got: {got:?}");
        assert_eq!(got[0].as_ref().unwrap(), &serde_json::json!({"a": 1}));
        assert!(got[1].is_err());
    }

    #[tokio::test]
    async fn stream_object_partial_fills_typed_mirror_progressively() {
        let c = client(ArrProvider::new(&["{\"title\":\"x\"", ",\"score\":5}"]));
        let got: Vec<ReportPartial> = c
            .stream_object_partial::<Report>(vec![Message::human("obj")])
            .await
            .unwrap()
            .map(|r| r.unwrap())
            .collect()
            .await;
        assert_eq!(got.len(), 2, "got: {got:?}");
        assert_eq!(got[0].title.as_deref(), Some("x"));
        assert_eq!(got[0].score, None);
        let last = got.last().unwrap();
        assert_eq!(last.title.as_deref(), Some("x"));
        assert_eq!(last.score, Some(5));
    }

    #[tokio::test]
    async fn stream_object_partial_skips_snapshots_that_do_not_fit_shape() {
        // A string `score` never fits `Option<u32>`; the snapshot is skipped,
        // not surfaced as an error, and later fitting snapshots still arrive.
        let c = client(ArrProvider::new(&[
            "{\"title\":\"a\",\"score\":\"hi\"",
            ",\"extra\":1}",
        ]));
        let got: Vec<Result<ReportPartial>> = c
            .stream_object_partial::<Report>(vec![Message::human("obj")])
            .await
            .unwrap()
            .collect()
            .await;
        assert!(got.is_empty(), "got: {got:?}");
    }

    #[tokio::test]
    async fn stream_object_partial_propagates_provider_error_and_stops() {
        let mut p = ArrProvider::new(&["{\"title\":\"x\""]);
        p.fail_after = true;
        let got: Vec<Result<ReportPartial>> = client(p)
            .stream_object_partial::<Report>(vec![Message::human("obj")])
            .await
            .unwrap()
            .collect()
            .await;
        assert_eq!(got.len(), 2, "got: {got:?}");
        assert_eq!(got[0].as_ref().unwrap().title.as_deref(), Some("x"));
        assert!(got[1].is_err());
    }
}
