//! Implementation of `#[derive(Partial)]`.
//!
//! Generates `<Name>Partial`, a mirror of a named-field struct with every
//! field wrapped in `Option`, plus the `cognis_core::Partial` impl linking the
//! two. Used so streamed JSON snapshots, which lack not-yet-emitted fields,
//! still deserialize. The serde attributes that decide which JSON keys a
//! field reads from are copied to the mirror; ones that cannot be honoured
//! there are rejected rather than silently dropped.

use proc_macro2::TokenStream;
use quote::{format_ident, quote};
use syn::punctuated::Punctuated;
use syn::{Attribute, Data, DeriveInput, Fields, LitStr, Meta, Token};

/// Struct-level serde keys copied onto the mirror.
const FORWARDED_STRUCT_KEYS: &[&str] = &["rename_all"];
/// Field-level serde keys copied onto the mirror's field.
const FORWARDED_FIELD_KEYS: &[&str] = &["rename", "alias"];
/// Serde keys with no bearing on the mirror: every mirror field is already
/// `#[serde(default)]`, and the mirror is never serialized.
const IGNORED_KEYS: &[&str] = &[
    "default",
    "skip_serializing",
    "skip_serializing_if",
    "serialize_with",
];

pub fn derive_partial(ast: DeriveInput) -> TokenStream {
    match expand(&ast) {
        Ok(ts) => ts,
        Err(e) => e.to_compile_error(),
    }
}

fn expand(ast: &DeriveInput) -> syn::Result<TokenStream> {
    let name = &ast.ident;
    if !ast.generics.params.is_empty() {
        return Err(syn::Error::new_spanned(
            &ast.generics,
            "Partial does not support generic structs",
        ));
    }
    let fields = match &ast.data {
        Data::Struct(s) => match &s.fields {
            Fields::Named(n) => &n.named,
            _ => {
                return Err(syn::Error::new_spanned(
                    name,
                    "Partial supports named-field structs only",
                ))
            }
        },
        _ => {
            return Err(syn::Error::new_spanned(
                name,
                "Partial supports structs only",
            ))
        }
    };

    let krate = crate_path(&ast.attrs)?;
    // The mirror derives `Deserialize` through the framework's own serde
    // re-export, so it compiles for callers who reach cognis-core only via
    // the umbrella crate and have no direct `serde` dependency.
    let serde_path = quote!(#krate::__serde).to_string().replace(' ', "");
    let struct_serde = forwarded_serde(&ast.attrs, FORWARDED_STRUCT_KEYS, "struct")?;

    let vis = &ast.vis;
    let partial_name = format_ident!("{}Partial", name);
    let mut decls = Vec::with_capacity(fields.len());
    for f in fields {
        let Some(id) = f.ident.as_ref() else { continue };
        let ty = &f.ty;
        let fvis = &f.vis;
        let field_serde = forwarded_serde(&f.attrs, FORWARDED_FIELD_KEYS, "field")?;
        decls.push(quote! {
            #[allow(missing_docs)]
            #[serde(default)]
            #(#[serde(#field_serde)])*
            #fvis #id: ::core::option::Option<#ty>
        });
    }

    let doc = format!(
        "Streaming mirror of `{name}`, generated by `#[derive(Partial)]`: the same \
         fields, each wrapped in `Option` and `None` until it has arrived. A field \
         that is already `Option<T>` on `{name}` is `Option<Option<T>>` here."
    );

    Ok(quote! {
        #[doc = #doc]
        #[derive(::core::fmt::Debug, ::core::default::Default, #krate::__serde::Deserialize)]
        #[serde(crate = #serde_path)]
        #(#[serde(#struct_serde)])*
        #vis struct #partial_name {
            #(#decls),*
        }

        impl #krate::Partial for #name {
            type Partial = #partial_name;
        }
    })
}

/// Collect the serde meta items to copy onto the mirror from `attrs`.
///
/// Keys in `forwarded` are returned, keys in [`IGNORED_KEYS`] are dropped,
/// and anything else is an error naming the key: silently ignoring, say,
/// `flatten` or `deserialize_with` would make the mirror read different JSON
/// than the source type does.
fn forwarded_serde(attrs: &[Attribute], forwarded: &[&str], site: &str) -> syn::Result<Vec<Meta>> {
    let mut out = Vec::new();
    for attr in attrs.iter().filter(|a| a.path().is_ident("serde")) {
        let metas = attr.parse_args_with(Punctuated::<Meta, Token![,]>::parse_terminated)?;
        for meta in metas {
            let key = meta
                .path()
                .get_ident()
                .map(|i| i.to_string())
                .unwrap_or_default();
            if forwarded.contains(&key.as_str()) {
                out.push(meta);
            } else if !IGNORED_KEYS.contains(&key.as_str()) {
                return Err(syn::Error::new_spanned(
                    &meta,
                    format!(
                        "Partial does not support the serde attribute `{key}` on a {site}; \
                         it copies only {} to the mirror",
                        forwarded
                            .iter()
                            .map(|k| format!("`{k}`"))
                            .collect::<Vec<_>>()
                            .join(", ")
                    ),
                ));
            }
        }
    }
    Ok(out)
}

/// Path to the crate that defines the `Partial` trait: the value of
/// `#[partial(crate = "...")]`, or `::cognis_core`.
fn crate_path(attrs: &[Attribute]) -> syn::Result<syn::Path> {
    let mut path: Option<syn::Path> = None;
    for attr in attrs.iter().filter(|a| a.path().is_ident("partial")) {
        attr.parse_nested_meta(|meta| {
            if meta.path.is_ident("crate") {
                let lit: LitStr = meta.value()?.parse()?;
                path = Some(anchored(&lit)?);
                Ok(())
            } else {
                let key = meta
                    .path
                    .get_ident()
                    .map(|i| i.to_string())
                    .unwrap_or_default();
                Err(meta.error(format!(
                    "unknown partial attribute `{key}`; expected `crate = \"path\"`"
                )))
            }
        })?;
    }
    Ok(path.unwrap_or_else(|| syn::parse_quote!(::cognis_core)))
}

/// Parse a crate path literal, anchoring it at the crate root (`::a::b`)
/// unless it is relative to the current crate (`crate::…`, `self::…`,
/// `super::…`) — the same rule the `GraphState` derive applies.
fn anchored(lit: &LitStr) -> syn::Result<syn::Path> {
    let mut path = lit.parse_with(syn::Path::parse_mod_style).map_err(|e| {
        syn::Error::new(
            lit.span(),
            format!("`crate` must be a module path such as \"cognis::cognis_core\": {e}"),
        )
    })?;
    let relative = path
        .segments
        .first()
        .is_some_and(|s| s.ident == "crate" || s.ident == "self" || s.ident == "super");
    if !relative && path.leading_colon.is_none() {
        path.leading_colon = Some(Default::default());
    }
    Ok(path)
}

#[cfg(test)]
mod tests {
    use super::*;
    use syn::parse_quote;

    fn expand_str(ast: DeriveInput) -> String {
        expand(&ast)
            .unwrap_or_else(|e| panic!("expected expansion, got error: {e}"))
            .to_string()
    }

    fn expand_err(ast: DeriveInput) -> String {
        match expand(&ast) {
            Ok(ts) => panic!("expected an error, got: {ts}"),
            Err(e) => e.to_string(),
        }
    }

    #[test]
    fn expand_forwards_struct_rename_all_to_mirror() {
        let out = expand_str(parse_quote! {
            #[serde(rename_all = "camelCase")]
            struct Report { report_title: String }
        });
        assert!(
            out.contains("# [serde (rename_all = \"camelCase\")]"),
            "got: {out}"
        );
    }

    #[test]
    fn expand_forwards_field_rename_and_alias_to_mirror() {
        let out = expand_str(parse_quote! {
            struct Report {
                #[serde(rename = "name", alias = "label")]
                title: String,
                #[serde(alias = "points", alias = "pts")]
                score: u32,
            }
        });
        assert!(out.contains("# [serde (rename = \"name\")]"), "got: {out}");
        assert!(out.contains("# [serde (alias = \"label\")]"), "got: {out}");
        assert!(out.contains("# [serde (alias = \"points\")]"), "got: {out}");
        assert!(out.contains("# [serde (alias = \"pts\")]"), "got: {out}");
    }

    #[test]
    fn expand_drops_default_and_serialize_only_keys() {
        let out = expand_str(parse_quote! {
            #[serde(default)]
            struct Report {
                #[serde(default = "make_title", skip_serializing_if = "String::is_empty")]
                title: String,
                #[serde(skip_serializing, serialize_with = "ser_score")]
                score: u32,
            }
        });
        for dropped in [
            "make_title",
            "skip_serializing",
            "serialize_with",
            "ser_score",
        ] {
            assert!(!out.contains(dropped), "`{dropped}` leaked into: {out}");
        }
    }

    #[test]
    fn expand_rejects_unsupported_field_key_and_names_it() {
        let err = expand_err(parse_quote! {
            struct Report {
                #[serde(flatten)]
                meta: Meta,
            }
        });
        assert!(err.contains("`flatten`"), "got: {err}");
    }

    #[test]
    fn expand_rejects_unsupported_key_when_mixed_with_supported_ones() {
        let err = expand_err(parse_quote! {
            struct Report {
                #[serde(rename = "t", deserialize_with = "de_title")]
                title: String,
            }
        });
        assert!(err.contains("`deserialize_with`"), "got: {err}");
    }

    #[test]
    fn expand_rejects_unsupported_struct_key_and_names_it() {
        let err = expand_err(parse_quote! {
            #[serde(rename_all = "camelCase", deny_unknown_fields)]
            struct Report { title: String }
        });
        assert!(err.contains("`deny_unknown_fields`"), "got: {err}");
    }

    #[test]
    fn expand_rejects_field_only_key_on_struct_and_struct_only_key_on_field() {
        let err = expand_err(parse_quote! {
            #[serde(alias = "R")]
            struct Report { title: String }
        });
        assert!(err.contains("`alias`"), "got: {err}");

        let err = expand_err(parse_quote! {
            struct Report {
                #[serde(rename_all = "camelCase")]
                title: String,
            }
        });
        assert!(err.contains("`rename_all`"), "got: {err}");
    }

    #[test]
    fn expand_defaults_to_cognis_core_crate_path() {
        let out = expand_str(parse_quote! {
            struct Report { title: String }
        });
        assert!(
            out.contains("impl :: cognis_core :: Partial for Report"),
            "got: {out}"
        );
        assert!(
            out.contains("# [serde (crate = \":: cognis_core :: __serde\")]")
                || out.contains("# [serde (crate = \"::cognis_core::__serde\")]"),
            "got: {out}"
        );
    }

    #[test]
    fn expand_uses_partial_crate_path_override() {
        let out = expand_str(parse_quote! {
            #[partial(crate = "cognis::cognis_core")]
            struct Report { title: String }
        });
        assert!(
            out.contains("impl :: cognis :: cognis_core :: Partial for Report"),
            "got: {out}"
        );

        let out = expand_str(parse_quote! {
            #[partial(crate = "crate::core_reexport")]
            struct Report { title: String }
        });
        assert!(
            out.contains("impl crate :: core_reexport :: Partial for Report"),
            "got: {out}"
        );
    }

    #[test]
    fn expand_rejects_unknown_partial_key_and_bad_crate_path() {
        let err = expand_err(parse_quote! {
            #[partial(krate = "cognis_core")]
            struct Report { title: String }
        });
        assert!(err.contains("`krate`"), "got: {err}");

        let err = expand_err(parse_quote! {
            #[partial(crate = "not a path!")]
            struct Report { title: String }
        });
        assert!(err.contains("crate"), "got: {err}");
    }

    #[test]
    fn expand_documents_mirror_and_allows_undocumented_fields() {
        let out = expand_str(parse_quote! {
            pub struct Report { pub title: String }
        });
        assert!(out.contains("# [doc ="), "got: {out}");
        assert!(out.contains("# [allow (missing_docs)]"), "got: {out}");
        assert!(out.contains("pub struct ReportPartial"), "got: {out}");
    }

    #[test]
    fn expand_wraps_option_field_in_a_second_option() {
        let out = expand_str(parse_quote! {
            struct Report { note: Option<String> }
        });
        assert!(
            out.contains("note : :: core :: option :: Option < Option < String > >"),
            "got: {out}"
        );
    }

    #[test]
    fn expand_rejects_enums_tuple_structs_and_generics() {
        assert!(expand_err(parse_quote! { enum E { A } }).contains("structs only"));
        assert!(expand_err(parse_quote! { struct T(u32); }).contains("named-field"));
        assert!(expand_err(parse_quote! { struct G<T> { t: T } }).contains("generic"));
    }
}
