//! Prebuilt chat agent.
//!
//! A high-level prebuilt agent that combines a chat model with optional tools
//! in a structured loop. Unlike the lower-level `create_react_agent` and
//! `create_tool_agent`, this module provides a self-contained `ChatAgent`
//! struct with builder-style configuration, typed state tracking, and
//! streaming event support.
//!
//! # Flow
//!
//! 1. Receive input messages
//! 2. Optionally prepend a system message
//! 3. Call the chat model
//! 4. If the model returns tool calls, execute them and loop back to step 3
//! 5. When no tool calls remain (or max iterations reached), return the final response
//!
//! # Example
//!
//! ```rust,no_run
//! use std::sync::Arc;
//! use langgraph::prebuilt::chat_agent::{ChatAgentConfig, create_chat_agent};
//!
//! // let agent = create_chat_agent(ChatAgentConfig {
//! //     model: my_model,
//! //     tools: vec![my_tool],
//! //     ..Default::default()
//! // });
//! // let response = agent.invoke(vec![Message::human("Hello")]).await.unwrap();
//! ```

use std::collections::HashMap;
use std::pin::Pin;
use std::sync::Arc;

use futures::Stream;
use serde::{Deserialize, Serialize};
use serde_json::Value;

use rustchain_core::language_models::chat_model::BaseChatModel;
use rustchain_core::messages::{Message, SystemMessage, ToolMessage};
use rustchain_core::tools::BaseTool;

use crate::errors::LangGraphError;

/// Configuration for creating a [`ChatAgent`].
pub struct ChatAgentConfig {
    /// The chat model to use for generating responses.
    pub model: Arc<dyn BaseChatModel>,
    /// Tools available to the agent. Can be empty for a simple chat agent.
    pub tools: Vec<Arc<dyn BaseTool>>,
    /// Optional system message prepended to every model invocation.
    pub system_message: Option<String>,
    /// Maximum number of model-tool loop iterations before stopping (default: 25).
    pub max_iterations: usize,
    /// Whether to include intermediate tool call steps in the response (default: false).
    pub return_intermediate_steps: bool,
    /// Whether to gracefully handle model parsing errors (default: true).
    pub handle_parsing_errors: bool,
}

impl Default for ChatAgentConfig {
    fn default() -> Self {
        Self {
            model: Arc::new(DefaultPlaceholderModel),
            tools: Vec::new(),
            system_message: None,
            max_iterations: 25,
            return_intermediate_steps: false,
            handle_parsing_errors: true,
        }
    }
}

/// The internal state of a chat agent during execution.
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct ChatAgentState {
    /// Full conversation history.
    pub messages: Vec<Message>,
    /// Tool call and result pairs recorded during execution.
    pub intermediate_steps: Vec<AgentStep>,
    /// Number of model-tool loop iterations completed.
    pub iteration_count: usize,
    /// Whether the agent has finished (no more tool calls or limit reached).
    pub is_finished: bool,
}

impl ChatAgentState {
    /// Create a new state from initial messages.
    pub fn new(messages: Vec<Message>) -> Self {
        Self {
            messages,
            intermediate_steps: Vec::new(),
            iteration_count: 0,
            is_finished: false,
        }
    }
}

/// A single tool invocation step: the call and its output.
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct AgentStep {
    /// Information about the tool call made by the model.
    pub tool_call: ToolCallInfo,
    /// The string output returned by the tool.
    pub tool_output: String,
}

/// Metadata about a tool call issued by the model.
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct ToolCallInfo {
    /// The name of the tool.
    pub name: String,
    /// The arguments passed to the tool.
    pub args: HashMap<String, Value>,
    /// The unique identifier for this tool call.
    pub id: String,
}

impl ToolCallInfo {
    /// Create a new `ToolCallInfo`.
    pub fn new(
        name: impl Into<String>,
        args: HashMap<String, Value>,
        id: impl Into<String>,
    ) -> Self {
        Self {
            name: name.into(),
            args,
            id: id.into(),
        }
    }
}

/// The final response from a chat agent invocation.
#[derive(Debug, Clone)]
pub struct ChatAgentResponse {
    /// The full conversation history including all AI responses and tool messages.
    pub messages: Vec<Message>,
    /// The final text output from the agent.
    pub output: String,
    /// Intermediate tool call steps (populated only if `return_intermediate_steps` is true).
    pub intermediate_steps: Vec<AgentStep>,
}

/// Events emitted during streaming chat agent execution.
#[derive(Debug, Clone)]
pub enum ChatAgentEvent {
    /// The model is about to be called.
    ModelStart,
    /// A token was generated by the model.
    ModelToken(String),
    /// The model finished generating a complete message.
    ModelEnd(Box<Message>),
    /// A tool is about to be executed.
    ToolStart {
        /// Name of the tool being called.
        name: String,
    },
    /// A tool finished executing.
    ToolEnd {
        /// Name of the tool that was called.
        name: String,
        /// The output returned by the tool.
        output: String,
    },
    /// The agent has finished and produced a final output.
    AgentFinish {
        /// The final response text.
        output: String,
    },
}

/// A prebuilt chat agent that combines a model with tools.
pub struct ChatAgent {
    model: Arc<dyn BaseChatModel>,
    tools: HashMap<String, Arc<dyn BaseTool>>,
    #[allow(dead_code)]
    tool_list: Vec<Arc<dyn BaseTool>>,
    system_message: Option<String>,
    max_iterations: usize,
    return_intermediate_steps: bool,
    handle_parsing_errors: bool,
}

impl ChatAgent {
    /// Set or override the system message.
    pub fn with_system_message(mut self, msg: impl Into<String>) -> Self {
        self.system_message = Some(msg.into());
        self
    }

    /// Set or override the maximum iteration count.
    pub fn with_max_iterations(mut self, n: usize) -> Self {
        self.max_iterations = n;
        self
    }

    /// Invoke the agent with a list of input messages.
    ///
    /// Runs the model-tool loop until the model produces a response without
    /// tool calls or the iteration limit is reached.
    pub async fn invoke(
        &self,
        messages: Vec<Message>,
    ) -> Result<ChatAgentResponse, LangGraphError> {
        let mut state = ChatAgentState::new(messages);

        // Prepend system message if configured and not already present.
        if let Some(ref sys) = self.system_message {
            let has_system = state
                .messages
                .iter()
                .any(|m| matches!(m, Message::System(_)));
            if !has_system {
                state
                    .messages
                    .insert(0, Message::System(SystemMessage::new(sys)));
            }
        }

        while !state.is_finished && state.iteration_count < self.max_iterations {
            // Call the model.
            let result = self
                .model
                ._generate(&state.messages, None)
                .await
                .map_err(|e| LangGraphError::Other(format!("Model error: {e}")))?;

            let generation = result
                .generations
                .into_iter()
                .next()
                .ok_or_else(|| LangGraphError::Other("No generations returned".into()))?;

            // Append AI message.
            state.messages.push(generation.message.clone());

            // Check for tool calls.
            let tool_calls = match &generation.message {
                Message::Ai(ai) if !ai.tool_calls.is_empty() => ai.tool_calls.clone(),
                _ => {
                    // No tool calls — we are done.
                    state.is_finished = true;
                    break;
                }
            };

            // No tools available but model requested them.
            if self.tools.is_empty() {
                state.is_finished = true;
                break;
            }

            // Execute each tool call.
            for tc in &tool_calls {
                let tool_call_id = tc.id.clone().unwrap_or_default();

                let output = if let Some(tool) = self.tools.get(&tc.name) {
                    let input =
                        rustchain_core::tools::types::ToolInput::Structured(tc.args.clone());
                    match tool.run(input, Some(&tool_call_id)).await {
                        Ok(v) => v.to_string(),
                        Err(e) => {
                            if self.handle_parsing_errors {
                                format!("Error: {e}")
                            } else {
                                return Err(LangGraphError::Other(format!("Tool error: {e}")));
                            }
                        }
                    }
                } else if self.handle_parsing_errors {
                    format!("Error: Tool '{}' not found", tc.name)
                } else {
                    return Err(LangGraphError::Other(format!(
                        "Tool '{}' not found",
                        tc.name
                    )));
                };

                // Record intermediate step.
                let step = AgentStep {
                    tool_call: ToolCallInfo {
                        name: tc.name.clone(),
                        args: tc.args.clone(),
                        id: tool_call_id.clone(),
                    },
                    tool_output: output.clone(),
                };
                state.intermediate_steps.push(step);

                // Add tool message to conversation.
                state
                    .messages
                    .push(Message::Tool(ToolMessage::new(&output, &tool_call_id)));
            }

            state.iteration_count += 1;
        }

        // Extract final output text.
        let output = state
            .messages
            .iter()
            .rev()
            .find_map(|m| match m {
                Message::Ai(ai) => Some(ai.base.content.text()),
                _ => None,
            })
            .unwrap_or_default();

        let intermediate_steps = if self.return_intermediate_steps {
            state.intermediate_steps.clone()
        } else {
            Vec::new()
        };

        Ok(ChatAgentResponse {
            messages: state.messages,
            output,
            intermediate_steps,
        })
    }

    /// Stream events from the agent execution.
    ///
    /// Returns a pinned stream of [`ChatAgentEvent`] values. This provides
    /// coarse-grained events (model start/end, tool start/end, agent finish)
    /// rather than token-level streaming.
    pub async fn stream(
        &self,
        messages: Vec<Message>,
    ) -> Result<Pin<Box<dyn Stream<Item = ChatAgentEvent> + Send + '_>>, LangGraphError> {
        let mut state = ChatAgentState::new(messages);

        // Prepend system message if configured.
        if let Some(ref sys) = self.system_message {
            let has_system = state
                .messages
                .iter()
                .any(|m| matches!(m, Message::System(_)));
            if !has_system {
                state
                    .messages
                    .insert(0, Message::System(SystemMessage::new(sys)));
            }
        }

        let mut events = Vec::new();

        while !state.is_finished && state.iteration_count < self.max_iterations {
            events.push(ChatAgentEvent::ModelStart);

            let result = self
                .model
                ._generate(&state.messages, None)
                .await
                .map_err(|e| LangGraphError::Other(format!("Model error: {e}")))?;

            let generation = result
                .generations
                .into_iter()
                .next()
                .ok_or_else(|| LangGraphError::Other("No generations returned".into()))?;

            events.push(ChatAgentEvent::ModelEnd(Box::new(
                generation.message.clone(),
            )));
            state.messages.push(generation.message.clone());

            let tool_calls = match &generation.message {
                Message::Ai(ai) if !ai.tool_calls.is_empty() => ai.tool_calls.clone(),
                _ => {
                    let output = generation.message.content().text();
                    events.push(ChatAgentEvent::AgentFinish { output });
                    state.is_finished = true;
                    break;
                }
            };

            if self.tools.is_empty() {
                let output = generation.message.content().text();
                events.push(ChatAgentEvent::AgentFinish { output });
                state.is_finished = true;
                break;
            }

            for tc in &tool_calls {
                let tool_call_id = tc.id.clone().unwrap_or_default();
                events.push(ChatAgentEvent::ToolStart {
                    name: tc.name.clone(),
                });

                let output = if let Some(tool) = self.tools.get(&tc.name) {
                    let input =
                        rustchain_core::tools::types::ToolInput::Structured(tc.args.clone());
                    match tool.run(input, Some(&tool_call_id)).await {
                        Ok(v) => v.to_string(),
                        Err(e) => format!("Error: {e}"),
                    }
                } else {
                    format!("Error: Tool '{}' not found", tc.name)
                };

                events.push(ChatAgentEvent::ToolEnd {
                    name: tc.name.clone(),
                    output: output.clone(),
                });

                state
                    .messages
                    .push(Message::Tool(ToolMessage::new(&output, &tool_call_id)));
            }

            state.iteration_count += 1;
        }

        // If we exited due to max iterations, emit a finish event.
        if !state.is_finished {
            let output = state
                .messages
                .iter()
                .rev()
                .find_map(|m| match m {
                    Message::Ai(ai) => Some(ai.base.content.text()),
                    _ => None,
                })
                .unwrap_or_default();
            events.push(ChatAgentEvent::AgentFinish { output });
        }

        Ok(Box::pin(futures::stream::iter(events)))
    }
}

/// Create a [`ChatAgent`] from the given configuration.
///
/// # Arguments
///
/// * `config` - Configuration specifying the model, tools, and behavior.
///
/// # Returns
///
/// A `ChatAgent` ready for invocation or streaming.
pub fn create_chat_agent(config: ChatAgentConfig) -> ChatAgent {
    let tools: HashMap<String, Arc<dyn BaseTool>> = config
        .tools
        .iter()
        .map(|t| (t.name().to_string(), t.clone()))
        .collect();

    ChatAgent {
        model: config.model,
        tool_list: config.tools,
        tools,
        system_message: config.system_message,
        max_iterations: config.max_iterations,
        return_intermediate_steps: config.return_intermediate_steps,
        handle_parsing_errors: config.handle_parsing_errors,
    }
}

/// Placeholder model used only to make `ChatAgentConfig::default()` compile.
/// Should never actually be invoked — always supply a real model.
struct DefaultPlaceholderModel;

#[async_trait::async_trait]
impl BaseChatModel for DefaultPlaceholderModel {
    async fn _generate(
        &self,
        _messages: &[Message],
        _stop: Option<&[String]>,
    ) -> rustchain_core::error::Result<rustchain_core::outputs::ChatResult> {
        Err(rustchain_core::error::RustChainError::Other(
            "DefaultPlaceholderModel: no model configured".into(),
        ))
    }

    fn llm_type(&self) -> &str {
        "placeholder"
    }
}

#[cfg(test)]
mod tests {
    use super::*;
    use rustchain_core::language_models::fake::FakeMessagesListChatModel;
    use rustchain_core::messages::{AIMessage, ToolCall};
    use rustchain_core::tools::types::{ToolInput, ToolOutput};
    use serde_json::json;

    /// A simple mock tool for testing.
    struct MockTool {
        name: String,
        description: String,
        result: String,
    }

    impl MockTool {
        fn new(name: &str, result: &str) -> Self {
            Self {
                name: name.to_string(),
                description: format!("Mock tool: {}", name),
                result: result.to_string(),
            }
        }
    }

    #[async_trait::async_trait]
    impl BaseTool for MockTool {
        fn name(&self) -> &str {
            &self.name
        }

        fn description(&self) -> &str {
            &self.description
        }

        async fn _run(&self, _input: ToolInput) -> rustchain_core::error::Result<ToolOutput> {
            Ok(ToolOutput::Content(Value::String(self.result.clone())))
        }
    }

    fn make_ai_with_tool_calls(content: &str, tool_calls: Vec<ToolCall>) -> Message {
        let mut ai = AIMessage::new(content);
        ai.tool_calls = tool_calls;
        Message::Ai(ai)
    }

    // ── Test 1: Create agent with config ──

    #[test]
    fn test_create_chat_agent_with_config() {
        let model = Arc::new(FakeMessagesListChatModel::new(vec![Message::Ai(
            AIMessage::new("hello"),
        )]));
        let tool: Arc<dyn BaseTool> = Arc::new(MockTool::new("search", "result"));
        let agent = create_chat_agent(ChatAgentConfig {
            model,
            tools: vec![tool],
            system_message: Some("You are helpful.".into()),
            max_iterations: 10,
            return_intermediate_steps: true,
            handle_parsing_errors: false,
        });
        assert_eq!(agent.max_iterations, 10);
        assert!(agent.system_message.is_some());
        assert_eq!(agent.tools.len(), 1);
        assert!(agent.tools.contains_key("search"));
    }

    // ── Test 2: Agent without tools returns direct response ──

    #[tokio::test]
    async fn test_chat_agent_without_tools_direct_response() {
        let model = Arc::new(FakeMessagesListChatModel::new(vec![Message::Ai(
            AIMessage::new("The capital of France is Paris."),
        )]));
        let agent = create_chat_agent(ChatAgentConfig {
            model,
            tools: vec![],
            ..Default::default()
        });

        let response = agent
            .invoke(vec![Message::human("What is the capital of France?")])
            .await
            .unwrap();
        assert_eq!(response.output, "The capital of France is Paris.");
        assert_eq!(response.messages.len(), 2); // human + ai
        assert!(response.intermediate_steps.is_empty());
    }

    // ── Test 3: Agent state initialization ──

    #[test]
    fn test_chat_agent_state_initialization() {
        let msgs = vec![Message::human("Hi"), Message::ai("Hello!")];
        let state = ChatAgentState::new(msgs.clone());
        assert_eq!(state.messages.len(), 2);
        assert!(state.intermediate_steps.is_empty());
        assert_eq!(state.iteration_count, 0);
        assert!(!state.is_finished);
    }

    // ── Test 4: Max iterations limit ──

    #[tokio::test]
    async fn test_chat_agent_max_iterations_limit() {
        // Model always returns a tool call — agent should stop at max_iterations.
        let tc = ToolCall {
            name: "search".to_string(),
            args: HashMap::new(),
            id: Some("call_1".to_string()),
        };
        let ai_with_tc = make_ai_with_tool_calls("", vec![tc]);
        let model = Arc::new(FakeMessagesListChatModel::new(vec![ai_with_tc]));
        let tool: Arc<dyn BaseTool> = Arc::new(MockTool::new("search", "result"));

        let agent = create_chat_agent(ChatAgentConfig {
            model,
            tools: vec![tool],
            max_iterations: 3,
            ..Default::default()
        });

        let response = agent
            .invoke(vec![Message::human("search forever")])
            .await
            .unwrap();

        // Should have stopped after 3 iterations.
        // Each iteration: AI message + tool message = 2 messages
        // Total: 1 (human) + 3 * 2 (ai + tool) = 7
        assert_eq!(response.messages.len(), 7);
    }

    // ── Test 5: Config defaults ──

    #[test]
    fn test_chat_agent_config_defaults() {
        let config = ChatAgentConfig {
            model: Arc::new(FakeMessagesListChatModel::new(vec![Message::Ai(
                AIMessage::new("x"),
            )])),
            ..Default::default()
        };
        assert_eq!(config.max_iterations, 25);
        assert!(!config.return_intermediate_steps);
        assert!(config.handle_parsing_errors);
        assert!(config.system_message.is_none());
        assert!(config.tools.is_empty());
    }

    // ── Test 6: System message injection ──

    #[tokio::test]
    async fn test_chat_agent_system_message_injection() {
        // Use ParrotFakeChatModel — it echoes the last message.
        // If system message is injected, the agent still responds to the user message.
        let model = Arc::new(FakeMessagesListChatModel::new(vec![Message::Ai(
            AIMessage::new("I am a helpful assistant"),
        )]));
        let agent = create_chat_agent(ChatAgentConfig {
            model,
            system_message: Some("You are a helpful assistant.".into()),
            ..Default::default()
        });

        let response = agent.invoke(vec![Message::human("Hello")]).await.unwrap();

        // Should have system + human + ai = 3 messages.
        assert_eq!(response.messages.len(), 3);
        assert!(matches!(response.messages[0], Message::System(_)));
        assert_eq!(response.output, "I am a helpful assistant");
    }

    // ── Test 7: AgentStep construction ──

    #[test]
    fn test_agent_step_construction() {
        let mut args = HashMap::new();
        args.insert("query".to_string(), json!("test"));

        let tool_call_info = ToolCallInfo::new("search", args.clone(), "call_42");
        assert_eq!(tool_call_info.name, "search");
        assert_eq!(tool_call_info.id, "call_42");
        assert_eq!(tool_call_info.args, args);

        let step = AgentStep {
            tool_call: tool_call_info,
            tool_output: "found it".to_string(),
        };
        assert_eq!(step.tool_output, "found it");
        assert_eq!(step.tool_call.name, "search");
    }

    // ── Test 8: ChatAgentResponse structure ──

    #[tokio::test]
    async fn test_chat_agent_response_structure() {
        let tc = ToolCall {
            name: "calculator".to_string(),
            args: {
                let mut m = HashMap::new();
                m.insert("expr".to_string(), json!("2+2"));
                m
            },
            id: Some("call_1".to_string()),
        };
        let ai_with_tc = make_ai_with_tool_calls("", vec![tc]);
        let ai_final = Message::Ai(AIMessage::new("The answer is 4"));

        let model = Arc::new(FakeMessagesListChatModel::new(vec![ai_with_tc, ai_final]));
        let tool: Arc<dyn BaseTool> = Arc::new(MockTool::new("calculator", "4"));

        let agent = create_chat_agent(ChatAgentConfig {
            model,
            tools: vec![tool],
            return_intermediate_steps: true,
            ..Default::default()
        });

        let response = agent
            .invoke(vec![Message::human("What is 2+2?")])
            .await
            .unwrap();

        assert_eq!(response.output, "The answer is 4");
        // human + ai(tool_call) + tool_result + ai(final) = 4
        assert_eq!(response.messages.len(), 4);
        assert_eq!(response.intermediate_steps.len(), 1);
        assert_eq!(response.intermediate_steps[0].tool_call.name, "calculator");
        assert_eq!(response.intermediate_steps[0].tool_output, "\"4\"");
    }

    // ── Test 9: Agent event types ──

    #[tokio::test]
    async fn test_chat_agent_event_types() {
        let model = Arc::new(FakeMessagesListChatModel::new(vec![Message::Ai(
            AIMessage::new("done"),
        )]));
        let agent = create_chat_agent(ChatAgentConfig {
            model,
            ..Default::default()
        });

        use futures::StreamExt;
        let stream = agent.stream(vec![Message::human("hi")]).await.unwrap();
        let events: Vec<_> = stream.collect().await;

        assert!(events.len() >= 3); // ModelStart, ModelEnd, AgentFinish
        assert!(matches!(events[0], ChatAgentEvent::ModelStart));
        assert!(matches!(events[1], ChatAgentEvent::ModelEnd(_)));
        assert!(matches!(
            events.last().unwrap(),
            ChatAgentEvent::AgentFinish { .. }
        ));
    }

    // ── Test 10: Builder-style configuration ──

    #[test]
    fn test_chat_agent_builder_style() {
        let model = Arc::new(FakeMessagesListChatModel::new(vec![Message::Ai(
            AIMessage::new("hello"),
        )]));
        let agent = create_chat_agent(ChatAgentConfig {
            model,
            ..Default::default()
        })
        .with_system_message("Be concise.")
        .with_max_iterations(5);

        assert_eq!(agent.system_message.as_deref(), Some("Be concise."));
        assert_eq!(agent.max_iterations, 5);
    }

    // ── Test 11: Handle empty message list ──

    #[tokio::test]
    async fn test_chat_agent_empty_messages() {
        let model = Arc::new(FakeMessagesListChatModel::new(vec![Message::Ai(
            AIMessage::new("No input received"),
        )]));
        let agent = create_chat_agent(ChatAgentConfig {
            model,
            ..Default::default()
        });

        let response = agent.invoke(vec![]).await.unwrap();
        assert_eq!(response.output, "No input received");
        // Only the AI response message.
        assert_eq!(response.messages.len(), 1);
    }

    // ── Test 12: Multiple tool scenario setup ──

    #[tokio::test]
    async fn test_chat_agent_multiple_tools() {
        let tc1 = ToolCall {
            name: "add".to_string(),
            args: {
                let mut m = HashMap::new();
                m.insert("a".to_string(), json!(1));
                m.insert("b".to_string(), json!(2));
                m
            },
            id: Some("call_1".to_string()),
        };
        let tc2 = ToolCall {
            name: "multiply".to_string(),
            args: {
                let mut m = HashMap::new();
                m.insert("a".to_string(), json!(3));
                m.insert("b".to_string(), json!(4));
                m
            },
            id: Some("call_2".to_string()),
        };
        let ai_with_tcs = make_ai_with_tool_calls("", vec![tc1, tc2]);
        let ai_final = Message::Ai(AIMessage::new("3 and 12"));

        let model = Arc::new(FakeMessagesListChatModel::new(vec![ai_with_tcs, ai_final]));
        let tools: Vec<Arc<dyn BaseTool>> = vec![
            Arc::new(MockTool::new("add", "3")),
            Arc::new(MockTool::new("multiply", "12")),
        ];

        let agent = create_chat_agent(ChatAgentConfig {
            model,
            tools,
            return_intermediate_steps: true,
            ..Default::default()
        });

        let response = agent
            .invoke(vec![Message::human("Add 1+2 and multiply 3*4")])
            .await
            .unwrap();

        assert_eq!(response.output, "3 and 12");
        // human + ai(2 tool_calls) + tool_result_1 + tool_result_2 + ai(final) = 5
        assert_eq!(response.messages.len(), 5);
        assert_eq!(response.intermediate_steps.len(), 2);
        assert_eq!(response.intermediate_steps[0].tool_call.name, "add");
        assert_eq!(response.intermediate_steps[1].tool_call.name, "multiply");
    }

    // ── Test 13: Stream events with tool calls ──

    #[tokio::test]
    async fn test_chat_agent_stream_with_tools() {
        let tc = ToolCall {
            name: "search".to_string(),
            args: HashMap::new(),
            id: Some("call_1".to_string()),
        };
        let ai_with_tc = make_ai_with_tool_calls("", vec![tc]);
        let ai_final = Message::Ai(AIMessage::new("Found it"));

        let model = Arc::new(FakeMessagesListChatModel::new(vec![ai_with_tc, ai_final]));
        let tool: Arc<dyn BaseTool> = Arc::new(MockTool::new("search", "result"));

        let agent = create_chat_agent(ChatAgentConfig {
            model,
            tools: vec![tool],
            ..Default::default()
        });

        use futures::StreamExt;
        let stream = agent
            .stream(vec![Message::human("search something")])
            .await
            .unwrap();
        let events: Vec<_> = stream.collect().await;

        // Expected events:
        // ModelStart, ModelEnd(ai_with_tc), ToolStart, ToolEnd, ModelStart, ModelEnd(ai_final), AgentFinish
        assert!(events.len() >= 7);
        assert!(matches!(events[0], ChatAgentEvent::ModelStart));
        assert!(matches!(events[2], ChatAgentEvent::ToolStart { .. }));
        assert!(matches!(events[3], ChatAgentEvent::ToolEnd { .. }));
        assert!(matches!(
            events.last().unwrap(),
            ChatAgentEvent::AgentFinish { .. }
        ));
    }

    // ── Test 14: System message not duplicated ──

    #[tokio::test]
    async fn test_chat_agent_system_message_not_duplicated() {
        let model = Arc::new(FakeMessagesListChatModel::new(vec![Message::Ai(
            AIMessage::new("ok"),
        )]));
        let agent = create_chat_agent(ChatAgentConfig {
            model,
            system_message: Some("System prompt".into()),
            ..Default::default()
        });

        // Input already has a system message.
        let response = agent
            .invoke(vec![
                Message::system("Existing system"),
                Message::human("Hi"),
            ])
            .await
            .unwrap();

        // Should not add another system message.
        let system_count = response
            .messages
            .iter()
            .filter(|m| matches!(m, Message::System(_)))
            .count();
        assert_eq!(system_count, 1);
    }
}
